parameters:
#    presta_cms_theme_basic.example.class: Presta\CMSThemeBasicBundle\Example

services:
#    presta_cms_theme_basic.example:
#        class: %presta_cms_theme_basic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
