presta_cms_core:
    themes:
        creative:
            name: creative
            description: Creative theme
            navigations: [main]
            template: PrestaCMSThemeBasicBundle:Theme/Creative:layout.html.twig
            screenshot: 'bundles/prestacmsthemebasic/theme/creative/screenshot.jpg'
            admin_style: 'bundles/prestacmsthemebasic/theme/creative/admin/admin.css'
            block_styles:
                - info
                - headline
            zones:
                top:
                    rows: 1
                    cols: 12
                    name: top
                    can_add_block: false
                    can_sort_block: false
                navigation:
                    rows: 1
                    cols: 12
                    name: navigation
                    can_add_block: false
                    can_sort_block: false
                content:
                    rows: 4
                    cols: 12
                    name: content
                    can_add_block: false
                    can_sort_block: false
                footer_left:
                    rows: 1
                    cols: 2
                    name: footer_left
                    can_add_block: false
                    can_sort_block: false
                    blocks:
                        editor:
                            type: presta_cms.block.simple
                            is_editable: true
                            is_deletable: false
                            position: 10
                            settings: {}
                footer_middle:
                    rows: 1
                    cols: 4
                    name: footer_middle
                    can_add_block: false
                    can_sort_block: false
                    blocks:
                        sitemap:
                            type: presta_cms.block.sitemap
                            is_editable: true
                            is_deletable: false
                            position: 10
                footer_right:
                    rows: 1
                    cols: 6
                    name: footer_right
                    can_add_block: false
                    can_sort_block: false
                    blocks: {}
            page_template:
                default:
                    name: default
                    path: PrestaCMSThemeBasicBundle:Theme/Creative/Page:default.html.twig
                    zones:
                        content:
                            rows: 1
                            cols: 12
                            name: content
                            can_add_block: false
                            can_sort_block: false
                            blocks:
                                editor:
                                    type: presta_cms.block.simple
                                    is_editable: true
                                    is_deletable: false
                                    position: 10
                left-sidebar:
                    name: left-sidebar
                    path: PrestaCMSThemeBasicBundle:Theme/Creative/Page:left-sidebar.html.twig
                    zones:
                        left:
                            rows: 1
                            cols: 2
                            name: left
                            can_add_block: false
                            can_sort_block: false
                            blocks:
                                editor:
                                    type: presta_cms.block.simple
                                    is_editable: true
                                    is_deletable: false
                                    position: 10
                        content:
                            rows: 1
                            cols: 10
                            name: content
                            can_add_block: false
                            can_sort_block: false
                            blocks:
                                editor:
                                    type: presta_cms.block.simple
                                    is_editable: true
                                    is_deletable: false
                                    position: 10
                right-sidebar:
                    name: right-sidebar
                    path: PrestaCMSThemeBasicBundle:Theme/Creative/Page:right-sidebar.html.twig
                    zones:
                        content:
                            rows: 1
                            cols: 10
                            name: content
                            can_add_block: false
                            can_sort_block: false
                            blocks:
                                editor:
                                    type: presta_cms.block.simple
                                    is_editable: true
                                    is_deletable: false
                                    position: 10
                        right:
                            rows: 1
                            cols: 2
                            name: right
                            can_add_block: false
                            can_sort_block: false
                            blocks:
                                editor:
                                    type: presta_cms.block.simple
                                    is_editable: true
                                    is_deletable: false
                                    position: 10
                sample:
                    name: sample
                    path: PrestaCMSThemeBasicBundle:Theme/Creative/Page:sample.html.twig
                    zones: {}

